Adding a Getting Started
devsecops/restacker pull request #14
Opened 2016-09-19 22:26 UTC by GrahamMThomas

When I first attempted to use Restacker I was totally lost and I realized it was because there was no Getting Started page. So I create one with my limited understanding to help those with no understanding. I also created a diagram hopefully explaining the relationship between the 4 main files. 

If something in my understanding is incorrect please tell me and I will fix it!

Graham

2016-09-19 23:37 UTC, pbnj requested changes
Great idea. Love the "Getting Started" document.
I'd like to request few minor changes with regards to wording to make it a bit clearer.

2016-09-19 23:38 UTC, pmbenjamin commented on docs/05-GETTING_STARTED.md
> +Keep tweaking this file until you can run `restacker list` and get a list of all the stacks.
This line should read:
> `restacker list` should return a list of stacks for a particular account

2016-09-19 23:40 UTC, pmbenjamin commented on docs/05-GETTING_STARTED.md
> +Once this is complete, you need to get your hands on a template JSON file.
Remove "once this is complete". You can reference the CloudFormation sample template file that will reside in `infrastructure/cloudformation` (currently pending PR)

2016-09-19 23:42 UTC, pmbenjamin commented on docs/05-GETTING_STARTED.md
> +After you have this you need to fill out your parameters.yml file. If your template has explanations for each field be sure to read them.
Remove "After you have this" - a bit superfluous.
Remove "If your template has explanations for each field be sure to read them" - not sure what you mean here.
You can reference the Parameter sample file that will reside in `infrastructure/parameters/` (currently in a pending PR)

2016-09-19 23:43 UTC, pmbenjamin commented on docs/05-GETTING_STARTED.md
> +After this, you may need to setup a userdata.sh file.
Remove "After this" - a bit superfluous.
You may reference the userdata sample file that will reside in `infrastructure/userdata/` (currently in a pending PR).

2016-09-19 23:46 UTC, pbnj requested changes
Update wording in Getting_Started.md document.

2016-09-19 23:48 UTC, pbnj approved these changes

2016-09-20 18:39 UTC, GrahamMThomas commented on docs/05-GETTING_STARTED.md
> +After you have this you need to fill out your parameters.yml file. If your template has explanations for each field be sure to read them.
In the template.json, there are descriptions for each field. These descriptions really helped me understand what to enter in each field.

2016-09-20 18:39 UTC, GrahamMThomas commented
Changes made.

2016-09-21 03:37 UTC, merged